name: 'JFrog Xray Build Scan'
description: 'Scans builds using JFrog Xray with specified watch'
inputs:
  github_repo:
    description: 'GitHub repository (owner/repo) to report scan results to'
    required: true
  build_name:
    description: 'Name of the build to scan'
    required: true
  build_number:
    description: 'Build number to scan'
    required: true
  watch_name:
    description: 'Name of the Xray watch to use for scanning'
    required: false
    default: 'ark-20863-security-watch'
  jfrog_user:
    description: 'JFrog username'
    required: true
  jfrog_password:
    description: 'JFrog password'
    required: true
  jfrog_url:
    description: 'JFrog URL'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Setup JFrog CLI
      uses: jfrog/setup-jfrog-cli@v4
      env:
        JF_USER: ${{ inputs.jfrog_user }}
        JF_PASSWORD: ${{ inputs.jfrog_password }}
        JF_URL: ${{ inputs.jfrog_url }}

    - name: Run Xray scan
      continue-on-error: true # Scan may find violations, remove once policy is enforced or all violations are resolved
      shell: bash
      run: |
        # Set variables
        WATCH_NAME="${{ inputs.watch_name }}"

        echo "Scan output will be saved to: $SCAN_JSON"

        echo "Xray build audit with watch: $WATCH_NAME"
        echo "View watch violations: ${{ inputs.jfrog_url }}/ui/watchesNew/edit/$WATCH_NAME?activeTab=violations"
        
        jf audit --watches "$WATCH_NAME" --format json > "$SCAN_JSON" 
      
    - name: Parse scan results
      id: parse-scan
      if: always()
      shell: bash
      run: |
        VIOLATIONS_COUNT=$(jq '[.[] | select(.violations != null) | .violations | length] | add // 0' "$SCAN_JSON")

        echo "Total violations found: $VIOLATIONS_COUNT"
        echo "violations_count=$VIOLATIONS_COUNT" >> $GITHUB_OUTPUT
        
        TABLE=$(jq -r '
          .[] 
          | select(.violations != null) | .violations[]? 
          | {
              issue_id: (.issue_id // "N/A"),
              component_ids: (
                if (.components and (.components | length > 0)) 
                then (.components | to_entries | map( .value.impact_paths[]? | .[].component_id ) | flatten | unique ) 
                else [] 
                end
              ),
              severity: (.severity // "N/A"),
              cves: (
                if (.cves and (.cves | type == "array" and length > 0))
                then (.cves | map(.cve) )
                else []
                end
              ),
              references: (
                if (.references and (.references | length > 0)) 
                then (.references ) 
                else [] 
                end
              )
            }
        ' "$SCAN_JSON" | jq -r -s 'group_by(.issue_id)[] | 
          [
            (.[0].issue_id),
            ( map(.component_ids[]) | unique | join(",")),
            ( map(.severity) | unique | join(",")),
            ( map(.cves[]) | unique | join(",")),
            ( map(.references[]) | unique | join(","))
          ] | @tsv
        ' )
        
        echo "| ID | Affected Component | Criticality | CVEs | Links |" > summary-table.md
        echo "|----|-------------------|-------------|------|-------|" >> summary-table.md

        if [ -n "$TABLE" ]; then
          echo "$TABLE" | awk '{print "| " $1 " | " $2 " | " $3 " | " $4 " | " $5 " |"}' >> summary-table.md
        else
          echo "| No violations found | - | - | - | - |" >> summary-table.md
        fi

        cat summary-table.md >> $GITHUB_STEP_SUMMARY

    - name: Upload scan results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: xray-scan-results-${{ inputs.build_name }}-${{ inputs.build_number }}
        path: "xray-scan-${{ inputs.build_name }}-${{ inputs.build_number }}.json"
        retention-days: 30
    